services:
    app:
        build:
            args:
                user: anvaro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: excelimport
        container_name: excelimport-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - excelimport

    db:
        image: mysql:8.0
        container_name: excelimport-db
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - excelimport

    nginx:
        image: nginx:alpine
        container_name: excelimport-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - excelimport

networks:
    excelimport:
        driver: bridge
